# Generated by Django 4.2.1 on 2023-05-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dependent',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dependent',
            name='rejected_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dependent',
            name='rejected_date',
            field=models.DateTimeField(null=True),
        ),
    ]
