# Generated by Django 4.2.1 on 2023-05-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisationclass'),
        ('dependents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='dependent_class',
        ),
        migrations.AddField(
            model_name='dependent',
            name='organisation_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.organisationclass'),
        ),
        migrations.DeleteModel(
            name='DependentClass',
        ),
    ]
